### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by YahitoII** [Cediner/Rise-of-Kingdoms-Bot#1]
How do I run the project? I already installed everything necessary, I only failed in the last step, running the project

**Comment by YahitoII** [comment]
RESTART: C:\Users\fabri\OneDrive\Escritorio\Rise-of-Kingdoms-Bot-1.4.3.060721_beta\main.py 
Traceback (most recent call last):
  File "C:\Users\fabri\OneDrive\Escritorio\Rise-of-Kingdoms-Bot-1.4.3.060721_beta\main.py", line 3, in <module>
    from gui.main_window import MainWindow
  File "C:\Users\fabri\OneDrive\Escritorio\Rise-of-Kingdoms-Bot-1.4.3.060721_beta\gui\main_window.py", line 5, in <module>
    from gui.device_list_frame import DeviceListFrame
  File "C:\Users\fabri\OneDrive\Escritorio\Rise-of-Kingdoms-Bot-1.4.3.060721_beta\gui\device_list_frame.py", line 3, in <module>
    from gui.selected_device_frame import SelectedDeviceFrame
  File "C:\Users\fabri\OneDrive\Escritorio\Rise-of-Kingdoms-Bot-1.4.3.060721_beta\gui\selected_device_frame.py", line 10, in <module>
    from bot_related.bot import Bot
  File "C:\Users\fabri\OneDrive\Escritorio\Rise-of-Kingdoms-Bot-1.4.3.060721_beta\bot_related\bot.py", line 5, in <module>
    from Task import Task
ModuleNotFoundError: No module named 'Task'

**Comment by Cediner** [comment]
I use pycharp for use. Not release.
Code - clone or Code - Download zip
Run main.py.

**Comment by YahitoII** [comment]
A new problem appeared when trying to execute

**Comment by YahitoII** [comment]
It was able to execute successfully, my question is why it does not attack the barbarians? he manages to select the troops, but he does not send them.
